// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DirichletForest
List DirichletForest(NumericMatrix X, NumericMatrix Y, int B, int d_max, int n_min, int m_try, int seed, std::string method);
RcppExport SEXP _DirichletForestParallel_DirichletForest(SEXP XSEXP, SEXP YSEXP, SEXP BSEXP, SEXP d_maxSEXP, SEXP n_minSEXP, SEXP m_trySEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type d_max(d_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_min(n_minSEXP);
    Rcpp::traits::input_parameter< int >::type m_try(m_trySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(DirichletForest(X, Y, B, d_max, n_min, m_try, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// PredictDirichletForest
List PredictDirichletForest(List forest_model, NumericMatrix X_new);
RcppExport SEXP _DirichletForestParallel_PredictDirichletForest(SEXP forest_modelSEXP, SEXP X_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest_model(forest_modelSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_new(X_newSEXP);
    rcpp_result_gen = Rcpp::wrap(PredictDirichletForest(forest_model, X_new));
    return rcpp_result_gen;
END_RCPP
}
// delete_dirichlet_forest_rcpp
void delete_dirichlet_forest_rcpp(List forest_model);
RcppExport SEXP _DirichletForestParallel_delete_dirichlet_forest_rcpp(SEXP forest_modelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest_model(forest_modelSEXP);
    delete_dirichlet_forest_rcpp(forest_model);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DirichletForestParallel_DirichletForest", (DL_FUNC) &_DirichletForestParallel_DirichletForest, 8},
    {"_DirichletForestParallel_PredictDirichletForest", (DL_FUNC) &_DirichletForestParallel_PredictDirichletForest, 2},
    {"_DirichletForestParallel_delete_dirichlet_forest_rcpp", (DL_FUNC) &_DirichletForestParallel_delete_dirichlet_forest_rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DirichletForestParallel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
