# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DirichletForest <- function(X, Y, B = 100L, d_max = 10L, n_min = 5L, m_try = -1L, seed = 123L, method = "mle") {
    .Call('_DirichletForestParallel_DirichletForest', PACKAGE = 'DirichletForestParallel', X, Y, B, d_max, n_min, m_try, seed, method)
}

PredictDirichletForest <- function(forest_model, X_new) {
    .Call('_DirichletForestParallel_PredictDirichletForest', PACKAGE = 'DirichletForestParallel', forest_model, X_new)
}

delete_dirichlet_forest_rcpp <- function(forest_model) {
    invisible(.Call('_DirichletForestParallel_delete_dirichlet_forest_rcpp', PACKAGE = 'DirichletForestParallel', forest_model))
}

